version: 2.1

executors:
  rust-executor:
    docker:
      - image: rust:latest

jobs:
  build:
    executor: rust-executor
    steps:
      - checkout
      - run:
          name: install cargo-web
          command: cargo install -f cargo-web;
      - run:
          name: build
          command: cargo build --verbose;
      - run:
          name: build web
          command: cargo web build --verbose --target wasm32-unknown-unknown;